config/routes.rb
RakeUi::Engine.routes.draw do
  root :to  => "rake_tasks#index"
  resources :rake_tasks
end

app/models/rake_ui/rake_task.rb
module RakeUi
  class RakeTask 
    include ActiveModel::Validations
    
    attr_accessor :command
    attr_accessor :arguments
    attr_accessor :id
    
    def initialize(opts={})
      @id, @command, @arguments = opts[:id], opts[:command], opts[:arguments]
    end
    
  end
end

app/controllers/rake_ui/application_controller.rb
module RakeUi
  class ApplicationController < ActionController::Base
  end
end

app/controllers/rake_ui/rake_tasks_controller.rb
module RakeUi
  class RakeTasksController < ApplicationController
    respond_to :js
    before_filter :load_tasks
    
    def index
      @rake_task = RakeUi::RakeTask.new
    end
    
    def create
      @rake_task = RakeUi::RakeTask.new(params[:rake_task])
      @rake_task.command = @tasks.select {|task| task['id'] == @rake_task.id }.pop['cmd']
      Kernel.system("#{@rake_task.command} #{@rake_task.arguments} &> #{Rails.root}/log/rake.log")  
      respond_to do |format|
        format.js {}
      end
    end
    
    private
    
    def load_tasks
      @tasks = JSON.parse(RAKE_TASKS)
    end
  end
end

app/helpers/rake_ui/application_helper.rb
module RakeUi
  module ApplicationHelper
    

    
  end
end

app/helpers/rake_ui/rake_tasks_helper.rb
module RakeUi
  module RakeTasksHelper
  end
end

app/views/layouts/rake_ui/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>RakeUi</title>
  <%= stylesheet_link_tag    "rake_ui/application" %>
  <%= javascript_include_tag "rake_ui/application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/rake_ui/rake_tasks/index.html.erb
<h1>Rake Tasks</h1>

<div style='width:100%'>
  <div style='float:left;width:35%'>
    <%= form_for @rake_task, :as => :rake_task, :url => rake_tasks_path, :remote => true do |f| %>
      <div>
        <label>Select a Rake Task</label>
        <%= f.select :id, @tasks.map{|t| [t['cmd'], t['id']]}.unshift(['-- select a task --',''])  %>
      </div>

      <div>
        <label>Optional Arguments</label>
        <%= f.text_area :arguments, :size => '30x4' %>
      </div>
      
      <div class='actions'>
        <%= f.submit 'run', :id => 'submit' %>
        <span id='loading' style='display:none;'><%= image_tag 'rake_ui/ajax-loader.gif', :valign => 'middle' %>Your task is running...</span>
      </div>
    <% end %>

    <div id='task_description'>
      <% @tasks.each do |task| %>
        <div id='<%= task['id'] %>' class='task_description' style='display:none;'><%= task['desc'] %></div>
      <% end %>
    </div>
  </div>

  <div style='float:left;width:55%'>
    <div><strong>Terminal Output</strong></div>
    <iframe src="http://localhost:8000" width="100%" height="600" frameborder='0'></iframe>
  </div>
</div>

<script type="text/javascript" charset="utf-8">
  $('#rake_task_id').change(function(){
    $('.task_description').hide();
    $( '#' + $(this).val() ).show();
  });
  
  $('#submit').click(function(){
    if($('#rake_task_id').val() == ''){
      alert('Select a Rake Task');
      return false;
    }
    $('#loading').show();
  });
</script>